version: "3.9"

services:
  djangoapp:
    container_name: django_stores_backend
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=020508
      - PG_DB=stores_db
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=stores_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=020508
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  sapui5_client:
    container_name: sapui5_client
    build: ../../../leverx-course/lx-course-dec23-andryieuski-yahor-ui5
    ports:
      - "8080:80"  # Порт, на котором будет работать Nginx в контейнере
    restart: always

volumes:
  pgdata: {}